In [1]:
# 数据收集
# 数据导入

import pandas as pd
df = pd.read_csv('data/employees.csv')

df

,employee_id,first_name,last_name,email,phone_number,job_id,salary,commission_pct,manager_id,department_id
0,100,Steven,King,SKING,515.123.4567,AD_PRES,24000.0,NaN,NaN,90.0
1,101,N_ann,Kochhar,NKOCHHAR,515.123.4568,AD_VP,17000.0,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,AD_VP,17000.0,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,IT_PROG,9000.0,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,IT_PROG,6000.0,NaN,103.0,60.0
...,...,...,...,...,...,...,...,...,...,...
102,202,Pat,Fay,PFAY,603.123.6666,MK_REP,6000.0,NaN,201.0,20.0
103,203,Susan,Mavris,SMAVRIS,515.123.7777,HR_REP,6500.0,NaN,101.0,40.0
104,204,Hermann,Baer,HBAER,515.123.8888,PR_REP,10000.0,NaN,101.0,70.0
105,205,Shelley,Higgins,SHIGGINS,515.123.8080,AC_MGR,12000.0,NaN,101.0,110.0
106,206,William,Gietz,WGIETZ,515.123.8181,AC_ACCOUNT,8300.0,NaN,205.0,110.0

In [17]:
print('数据类型:',type(df))
print('每个列的数据类型:\n',df.dtypes)

print('salary平均值:',df.salary.mean())

数据类型: <class 'pandas.DataFrame'>
每个列的数据类型:
 employee_id         int64
first_name            str
last_name             str
email                 str
phone_number          str
job_id                str
salary            float64
commission_pct    float64
manager_id        float64
department_id     float64
dtype: object
salary平均值: 6461.682242990654

In [18]:
# 数据的导出
df = df.tail()
df
df.to_csv('data/export/employees_export_fiveLine.csv')

In [20]:
# json数据
df = pd.read_json('data/data1.json')
print(df)
print(type(df))

   id name  age
0   1   张三   25
1   2   李四   30
2   3   王五   28
<class 'pandas.DataFrame'>

In [21]:
# 复杂一点的数据处理方式
df = pd.read_json('data/test.json')
print(df)
print(type(df))

                                               users
0  {'id': 1, 'name': '张三', 'age': 28, 'email': 'z...
1  {'id': 2, 'name': '李四', 'age': 35, 'email': 'l...
2  {'id': 3, 'name': '王五', 'age': 24, 'email': 'w...
<class 'pandas.DataFrame'>

In [27]:
# 使用json库中的load方法处理复杂的json数据
import json
with open('data/test.json','r',encoding='utf-8') as f:
    data = json.load(f)
print(data)
print(type(data))

df = pd.DataFrame(data['users'])
print(df)
print(type(df))

{'users': [{'id': 1, 'name': '张三', 'age': 28, 'email': 'zhangsan@example.com', 'is_active': True, 'join_date': '2022-03-15'}, {'id': 2, 'name': '李四', 'age': 35, 'email': 'lisi@example.com', 'is_active': False, 'join_date': '2021-11-02'}, {'id': 3, 'name': '王五', 'age': 24, 'email': 'wangwu@example.com', 'is_active': True, 'join_date': '2023-01-20'}]}
<class 'dict'>
   id name  age                 email  is_active   join_date
0   1   张三   28  zhangsan@example.com       True  2022-03-15
1   2   李四   35      lisi@example.com      False  2021-11-02
2   3   王五   24    wangwu@example.com       True  2023-01-20
<class 'pandas.DataFrame'>

In [ ]:
# 缺失值的处理
import pandas as pd
import numpy as np

s = pd.Series([1,2,np.nan,4,5,None,pd.NA])
print(s)

h = pd.DataFrame([[None,2,3],[4,np.nan,6],[7,8,pd.NA]])
print(h)

print('1.判断缺失值')
print(s.isnull())
print('2.判断缺失值')
print(s.isna())
print('3.判断缺失值')
print(h.isnull())
print('4.判断缺失值')
print(h.isna())

0       1
1       2
2     NaN
3       4
4       5
5    None
6    <NA>
dtype: object
     0    1     2
0  NaN  2.0     3
1  4.0  NaN     6
2  7.0  8.0  <NA>
1.判断缺失值
0    False
1    False
2     True
3    False
4    False
5     True
6     True
dtype: bool
2.判断缺失值
0    False
1    False
2     True
3    False
4    False
5     True
6     True
dtype: bool
3.判断缺失值
       0      1      2
0   True  False  False
1  False   True  False
2  False  False   True
4.判断缺失值
       0      1      2
0   True  False  False
1  False   True  False
2  False  False   True
5.缺失值数量
0    1
1    1
2    1
dtype: int64

In [36]:
# 缺失值数量
print(h.isnull().sum())
print(s.isna().sum())

0    1
1    1
2    1
dtype: int64
3

In [40]:
# 剔除缺失值
print(s.dropna())
print(s)

# 只要有一个缺失值，就剔除整行
print(h.dropna())
print(h)

print(h.dropna(how='all'))  # 只有当整行都是缺失值时，才会剔除整行
print(h)

0    1
1    2
3    4
4    5
dtype: object
0       1
1       2
2     NaN
3       4
4       5
5    None
6    <NA>
dtype: object
Empty DataFrame
Columns: [0, 1, 2]
Index: []
     0    1     2
0  NaN  2.0     3
1  4.0  NaN     6
2  7.0  8.0  <NA>
     0    1     2
0  NaN  2.0     3
1  4.0  NaN     6
2  7.0  8.0  <NA>
     0    1     2
0  NaN  2.0     3
1  4.0  NaN     6
2  7.0  8.0  <NA>

In [44]:
# 根据条件剔除缺失值
h = pd.DataFrame([[None,pd.NA,3],[4,np.nan,6],[7,8,pd.NA]])

print(h.dropna(thresh=2))  # 只有当整行非缺失值的数量大于等于2时，才会剔除整行
print(h)

     0    1     2
1  4.0  NaN     6
2  7.0    8  <NA>
     0     1     2
0  NaN  <NA>     3
1  4.0   NaN     6
2  7.0     8  <NA>

In [ ]:
# 删除一整列    
# axis  表示列方向上
print(h.dropna(axis=1,thresh=2))
print(h)

     0     2
0  NaN     3
1  4.0     6
2  7.0  <NA>
     0     1     2
0  NaN  <NA>     3
1  4.0   NaN     6
2  7.0     8  <NA>

In [ ]:
# 根据列名剔除缺失值
h = pd.DataFrame([[None,pd.NA,3],[4,np.nan,6],[7,8,pd.NA]],columns=['a','b','c'])
print(h.dropna(subset=['a']))  # 只有当整行a列非缺失值的数量大于等于1时，才会剔除整行
print(h)

     a    b     c
1  4.0  NaN     6
2  7.0    8  <NA>
     a     b     c
0  NaN  <NA>     3
1  4.0   NaN     6
2  7.0     8  <NA>

In [5]:
# 填充缺失值
df = pd.read_csv('data/weather_withna.csv')
df.isna().sum()

# 使用字典填充缺失值，key为列名，value为填充值
print(df.fillna({'temp_max':20,'wind':2.5}).tail())

# 使用统计值填充缺失值
print(df.fillna(df[['wind']].mean()).tail())

# 根据缺失值周边数据填充缺失值
print(df.ffill().tail())    # 前向填充
print(df.bfill().tail())    # 后向填充

            date  precipitation  temp_max  temp_min  wind weather
1456  2015-12-27            NaN      20.0       NaN   2.5     NaN
1457  2015-12-28            NaN      20.0       NaN   2.5     NaN
1458  2015-12-29            NaN      20.0       NaN   2.5     NaN
1459  2015-12-30            NaN      20.0       NaN   2.5     NaN
1460  2015-12-31           20.6      12.2       5.0   3.8    rain
            date  precipitation  temp_max  temp_min      wind weather
1456  2015-12-27            NaN       NaN       NaN  3.242055     NaN
1457  2015-12-28            NaN       NaN       NaN  3.242055     NaN
1458  2015-12-29            NaN       NaN       NaN  3.242055     NaN
1459  2015-12-30            NaN       NaN       NaN  3.242055     NaN
1460  2015-12-31           20.6      12.2       5.0  3.800000    rain
            date  precipitation  temp_max  temp_min  wind weather
1456  2015-12-27            0.0      11.1       4.4   4.8     sun
1457  2015-12-28            0.0      11.1       4.4   4.8     sun
1458  2015-12-29            0.0      11.1       4.4   4.8     sun
1459  2015-12-30            0.0      11.1       4.4   4.8     sun
1460  2015-12-31           20.6      12.2       5.0   3.8    rain
            date  precipitation  temp_max  temp_min  wind weather
1456  2015-12-27           20.6      12.2       5.0   3.8    rain
1457  2015-12-28           20.6      12.2       5.0   3.8    rain
1458  2015-12-29           20.6      12.2       5.0   3.8    rain
1459  2015-12-30           20.6      12.2       5.0   3.8    rain
1460  2015-12-31           20.6      12.2       5.0   3.8    rain

In [ ]:
data = {
    "name":["alice","bob","carol","charlie","bob","alice"],
    "age":[18,20,22,24,26,18],
    "city":["bj","sh","gz","sz","bj","bj"]
}

df = pd.DataFrame(data)

      name  age city
0    alice   18   bj
1      bob   20   sh
2    carol   22   gz
3  charlie   24   sz
4      bob   26   bj
5    alice   18   bj

In [17]:
df.duplicated()

# 删除重复值
print(df.drop_duplicates())

print('-----------------')

# 根据列名去重
print(df.drop_duplicates(subset=['name']))

print('-----------------')

# 根据最新数据去重
print(df.drop_duplicates(subset=['name'],keep='last'))

      name  age city
0    alice   18   bj
1      bob   20   sh
2    carol   22   gz
3  charlie   24   sz
4      bob   26   bj
-----------------
      name  age city
0    alice   18   bj
1      bob   20   sh
2    carol   22   gz
3  charlie   24   sz
-----------------
      name  age city
2    carol   22   gz
3  charlie   24   sz
4      bob   26   bj
5    alice   18   bj

In [20]:
# 数据类型转换
df = pd.read_csv('data/sleep.csv')
df
df.dtypes

person_id                    int64
gender                         str
age                          int64
occupation                     str
sleep_duration             float64
sleep_quality              float64
physical_activity_level      int64
stress_level                 int64
bmi_category                   str
blood_pressure                 str
heart_rate                   int64
daily_steps                  int64
sleep_disorder                 str
dtype: object

In [21]:
df['age'] = df['age'].astype('int16')
df.dtypes

person_id                    int64
gender                         str
age                          int16
occupation                     str
sleep_duration             float64
sleep_quality              float64
physical_activity_level      int64
stress_level                 int64
bmi_category                   str
blood_pressure                 str
heart_rate                   int64
daily_steps                  int64
sleep_disorder                 str
dtype: object

In [ ]:
df.gender
df['gender'] = df['gender'].astype('category')  # 转换为分类类型,提高效率

df.dtypes
df.gender

0        Male
1      Female
2        Male
3        Male
4        Male
        ...
395    Female
396    Female
397    Female
398    Female
399      Male
Name: gender, Length: 400, dtype: category
Categories (2, str): ['Female', 'Male']

In [ ]:
df['is_male'] = df['gender'].map({'Male': True, 'Female': False})   # 映射为布尔值
df.is_male

0       True
1      False
2       True
3       True
4       True
       ...
395    False
396    False
397    False
398    False
399     True
Name: is_male, Length: 400, dtype: category
Categories (2, bool): [False, True]

In [ ]:
# 数据变形
import pandas as pd
data = {
    'ID': [1, 2, 3, 4, 5],
    'Name': ['张三', '李四', '王五', '赵六', '钱七'],
    'Math': [80, 90, 75, 95, 88],
    'English': [95, 85, 90, 88, 92],
    'Physics': [88, 92, 85, 90, 95],
   }


df = pd.DataFrame(data)
df
df.T    # 转置

          0   1   2   3   4
ID        1   2   3   4   5
Name     张三  李四  王五  赵六  钱七
Math     80  90  75  95  88
English  95  85  90  88  92
Physics  88  92  85  90  95

In [ ]:
# 宽表转换成长表，将每个科目转换为一行，包含ID、姓名、科目和成绩四列
df2 = pd.melt(df, id_vars=['ID', 'Name'], var_name='Subject', value_name='Score')
df2.sort_values('Name')

    ID Name  Subject  Score
0    1   张三     Math     80
5    1   张三  English     95
10   1   张三  Physics     88
1    2   李四     Math     90
6    2   李四  English     85
11   2   李四  Physics     92
2    3   王五     Math     75
7    3   王五  English     90
12   3   王五  Physics     85
3    4   赵六     Math     95
8    4   赵六  English     88
13   4   赵六  Physics     90
4    5   钱七     Math     88
9    5   钱七  English     92
14   5   钱七  Physics     95

In [33]:
# 长表转宽表
pd.pivot(df2,index=['ID','Name'],columns='Subject',values='Score')

Subject  English  Math  Physics
ID Name
1  张三         95    80       88
2  李四         85    90       92
3  王五         90    75       85
4  赵六         88    95       90
5  钱七         92    88       95

In [4]:
# 分列
import pandas as pd
data = {
    'ID': [1, 2, 3, 4, 5],
    'Name': ['张三', '李四', '李五', '赵六', '张七'],
    'Math': [80, 90, 75, 95, 88],
    'English': [95, 85, 90, 88, 92],
    'Physics': [88, 92, 85, 90, 95],
   }

df = pd.DataFrame(data)
df


df['Name'] = df['Name'].str[0] + ' ' + df['Name'].str[1:]

In [6]:
# 将姓名列拆分成第一个和最后一个单词
df[['First','Last']] = df['Name'].str.split(" ",expand=True)
df

   ID Name  Math  English  Physics First Last
0   1  张 三    80       95       88     张    三
1   2  李 四    90       85       92     李    四
2   3  李 五    75       90       85     李    五
3   4  赵 六    95       88       90     赵    六
4   5  张 七    88       92       95     张    七

In [7]:
df = pd.read_csv('data/sleep.csv')
df.head()

df = df[['person_id','blood_pressure']]

df[['high_pressure','low_pressure']] = df['blood_pressure'].str.split('/',expand=True)
df['high_pressure'] = df['high_pressure'].astype('int64')
df['low_pressure'] = df['low_pressure'].astype('int64')
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   person_id       400 non-null    int64
 1   blood_pressure  400 non-null    str
 2   high_pressure   400 non-null    int64
 3   low_pressure    400 non-null    int64
dtypes: int64(3), str(1)
memory usage: 12.6 KB

In [8]:
# 数据分箱  pd.cut(x,bins,labels)
# 将数据分割成多个区间
df = pd.read_csv('data/employees.csv')
df

,employee_id,first_name,last_name,email,phone_number,job_id,salary,commission_pct,manager_id,department_id
0,100,Steven,King,SKING,515.123.4567,AD_PRES,24000.0,NaN,NaN,90.0
1,101,N_ann,Kochhar,NKOCHHAR,515.123.4568,AD_VP,17000.0,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,AD_VP,17000.0,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,IT_PROG,9000.0,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,IT_PROG,6000.0,NaN,103.0,60.0
...,...,...,...,...,...,...,...,...,...,...
102,202,Pat,Fay,PFAY,603.123.6666,MK_REP,6000.0,NaN,201.0,20.0
103,203,Susan,Mavris,SMAVRIS,515.123.7777,HR_REP,6500.0,NaN,101.0,40.0
104,204,Hermann,Baer,HBAER,515.123.8888,PR_REP,10000.0,NaN,101.0,70.0
105,205,Shelley,Higgins,SHIGGINS,515.123.8080,AC_MGR,12000.0,NaN,101.0,110.0
106,206,William,Gietz,WGIETZ,515.123.8181,AC_ACCOUNT,8300.0,NaN,205.0,110.0

In [9]:
df1 = df.head(10)[['employee_id','salary']]

df1

   employee_id   salary
0          100  24000.0
1          101  17000.0
2          102  17000.0
3          103   9000.0
4          104   6000.0
5          105   4800.0
6          106   4800.0
7          107   4200.0
8          108  12000.0
9          109   9000.0

In [ ]:
# 数据分箱
pd.cut(df1['salary'],bins=3)
pd.cut(df1['salary'],bins=3).value_counts()

salary
(4180.2, 10800.0]     6
(10800.0, 17400.0]    3
(17400.0, 24000.0]    1
Name: count, dtype: int64

In [17]:
# 设定分箱区间
pd.cut(df1['salary'],bins=[0,10000,20000,30000])

df1['收入范围'] =pd.cut(df1['salary'],bins=[0,10000,20000,30000],labels=['低','中','高'])
df1

   employee_id   salary 收入范围
0          100  24000.0    高
1          101  17000.0    中
2          102  17000.0    中
3          103   9000.0    低
4          104   6000.0    低
5          105   4800.0    低
6          106   4800.0    低
7          107   4200.0    低
8          108  12000.0    中
9          109   9000.0    低

In [19]:
# 等分
pd.qcut(df1['salary'],q=3).value_counts()

salary
(4199.999, 6000.0]    4
(6000.0, 12000.0]     3
(12000.0, 24000.0]    3
Name: count, dtype: int64

In [12]:
import pandas as pd
import numpy as np

df = pd.read_csv('data/sleep.csv')
df1 = df.head()
df1 = df[['person_id','sleep_quality','gender']]
df1

     person_id  sleep_quality  gender
0            1            7.0    Male
1            2            4.9  Female
2            3            6.0    Male
3            4           10.0    Male
4            5            9.5    Male
..         ...            ...     ...
395        396            7.9  Female
396        397            6.1  Female
397        398            6.5  Female
398        399            9.1  Female
399        400            7.0    Male

[400 rows x 3 columns]

In [13]:
df1['睡眠质量'] = pd.cut(df1['sleep_quality'], bins=3,labels=['差','中','好'])
df1

     person_id  sleep_quality  gender 睡眠质量
0            1            7.0    Male    中
1            2            4.9  Female    中
2            3            6.0    Male    中
3            4           10.0    Male    好
4            5            9.5    Male    好
..         ...            ...     ...  ...
395        396            7.9  Female    好
396        397            6.1  Female    中
397        398            6.5  Female    中
398        399            9.1  Female    好
399        400            7.0    Male    中

[400 rows x 4 columns]

In [17]:
# 数据分箱只能用于数值型数据，如果要分类字符串类型等，可以设置字符串为category类型
print(df1['睡眠质量'].value_counts())

print(df1['gender'].astype('category'))

睡眠质量
中    206
好    129
差     65
Name: count, dtype: int64
0        Male
1      Female
2        Male
3        Male
4        Male
        ...
395    Female
396    Female
397    Female
398    Female
399      Male
Name: gender, Length: 400, dtype: category
Categories (2, str): ['Female', 'Male']

In [49]:
# 数据转换，重命名，设置索引名字，列名修改
df = pd.DataFrame({
    'person_id': ["001", "002", "033", "044", "055"],
    'sleep_quality': [5, 4, 3, 2, 1],
    'gender': ['男', '女', '男', '女', '男']
})

print(df)
print("-"*20)
df.set_index('person_id',inplace=True)    # 设置索引为person_id列
print(df)

print("-"*20)

df.reset_index(inplace=True)
print(df)

print("-"*20)

df.rename(columns={'sleep_quality':'睡眠质量'},index={0:4},inplace=True)

print(df)
# print('-'*20)

  person_id  sleep_quality gender
0       001              5      男
1       002              4      女
2       033              3      男
3       044              2      女
4       055              1      男
--------------------
           sleep_quality gender
person_id
001                    5      男
002                    4      女
033                    3      男
044                    2      女
055                    1      男
--------------------
  person_id  sleep_quality gender
0       001              5      男
1       002              4      女
2       033              3      男
3       044              2      女
4       055              1      男
--------------------
  person_id  睡眠质量 gender
4       001     5      男
1       002     4      女
2       033     3      男
3       044     2      女
4       055     1      男

RcLepfmCKeMLXTLmHn@163.com