In [1]:
import pandas as pd

In [7]:
# 时间数据的处理
d = pd.Timestamp('2026-04-21')
print(d)
print(type(d))
print('年份:',d.year)
print('月份:',d.month)
print('日期:',d.day)

print('时间:',d.minute,d.second)
print('季度:',d.quarter)
print('是否是月底:',d.is_month_end)
print('星期几:',d.day_name())

print('转换为天数',d.to_period('D'))
print('转换为季度',d.to_period('Q'))
print('转换为年份',d.to_period('Y'))
print('转换为月份',d.to_period('M'))
print('转换为周',d.to_period('W'))

2026-04-21 00:00:00
<class 'pandas.Timestamp'>
年份: 2026
月份: 4
日期: 21
时间: 0 0
季度: 2
是否是月底: False
星期几: Tuesday
转换为天数 2026-04-21
转换为季度 2026Q2
转换为年份 2026
转换为月份 2026-04
转换为周 2026-04-20/2026-04-26

In [12]:
# 字符串转换为日期
# d = pd.to_datetime('2023-01-01')
d = pd.to_datetime('2026-04-22T23:05:14.826+08:00')
print(d)
print(type(d))
print('年份:',d.year)
print('月份:',d.month)
print('日期:',d.day)

2026-04-22 23:05:14.826000+08:00
<class 'pandas.Timestamp'>
年份: 2026
月份: 4
日期: 22

In [17]:
df = pd.DataFrame({
    'sale':[100,200,300],
    'date':['20260301','20260302','20260303']
})

df['datetime'] = pd.to_datetime(df['date'])
print(df)
print(df['datetime'])
df['week'] = df['datetime'].dt.day_name()
print(df)
df['year'] = df['datetime'].dt.year
print(df)

   sale      date   datetime
0   100  20260301 2026-03-01
1   200  20260302 2026-03-02
2   300  20260303 2026-03-03
0   2026-03-01
1   2026-03-02
2   2026-03-03
Name: datetime, dtype: datetime64[us]
   sale      date   datetime     week
0   100  20260301 2026-03-01   Sunday
1   200  20260302 2026-03-02   Monday
2   300  20260303 2026-03-03  Tuesday
   sale      date   datetime     week  year
0   100  20260301 2026-03-01   Sunday  2026
1   200  20260302 2026-03-02   Monday  2026
2   300  20260303 2026-03-03  Tuesday  2026

In [20]:
df = pd.read_csv('data/weather.csv')

df

            date  precipitation  temp_max  temp_min  wind  weather
0     2012-01-01            0.0      12.8       5.0   4.7  drizzle
1     2012-01-02           10.9      10.6       2.8   4.5     rain
2     2012-01-03            0.8      11.7       7.2   2.3     rain
3     2012-01-04           20.3      12.2       5.6   4.7     rain
4     2012-01-05            1.3       8.9       2.8   6.1     rain
...          ...            ...       ...       ...   ...      ...
1456  2015-12-27            8.6       4.4       1.7   2.9     rain
1457  2015-12-28            1.5       5.0       1.7   1.3     rain
1458  2015-12-29            0.0       7.2       0.6   2.6      fog
1459  2015-12-30            0.0       5.6      -1.0   3.4      sun
1460  2015-12-31            0.0       5.6      -2.1   3.5      sun

[1461 rows x 6 columns]

In [24]:
df['datatime'] = pd.to_datetime(df['date'])
df
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 1461 entries, 0 to 1460
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           1461 non-null   str
 1   precipitation  1461 non-null   float64
 2   temp_max       1461 non-null   float64
 3   temp_min       1461 non-null   float64
 4   wind           1461 non-null   float64
 5   weather        1461 non-null   str
 6   datatime       1461 non-null   datetime64[us]
dtypes: datetime64[us](1), float64(4), str(2)
memory usage: 80.0 KB
None

In [40]:
# 读取文件时将指定的列转换为日期类型
df = pd.read_csv('data/weather.csv',parse_dates=['date'])
df
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 1461 entries, 0 to 1460
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           1461 non-null   datetime64[us]
 1   precipitation  1461 non-null   float64
 2   temp_max       1461 non-null   float64
 3   temp_min       1461 non-null   float64
 4   wind           1461 non-null   float64
 5   weather        1461 non-null   str
dtypes: datetime64[us](1), float64(4), str(1)
memory usage: 68.6 KB
None

In [41]:
# 日期作为索引
df.set_index('date',inplace=True)

df
df.info()
print(type(df.index))

<class 'pandas.DataFrame'>
DatetimeIndex: 1461 entries, 2012-01-01 to 2015-12-31
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   precipitation  1461 non-null   float64
 1   temp_max       1461 non-null   float64
 2   temp_min       1461 non-null   float64
 3   wind           1461 non-null   float64
 4   weather        1461 non-null   str
dtypes: float64(4), str(1)
memory usage: 68.5 KB
<class 'pandas.DatetimeIndex'>

In [53]:
df = pd.read_csv('data/weather.csv',parse_dates=['date'])
df.set_index('date',inplace=True)
# 将日期作为索引后可以方便地进行时间范围的筛选
print(df.loc['2013-01':'2023-02'])
df = df.loc["2013-01":"2023-02"]
df

            precipitation  temp_max  temp_min  wind weather
date
2013-01-01            0.0       5.0      -2.8   2.7     sun
2013-01-02            0.0       6.1      -1.1   3.2     sun
2013-01-03            4.1       6.7      -1.7   3.0    rain
2013-01-04            2.5      10.0       2.2   2.8    rain
2013-01-05            3.0       6.7       4.4   3.1    rain
...                   ...       ...       ...   ...     ...
2015-12-27            8.6       4.4       1.7   2.9    rain
2015-12-28            1.5       5.0       1.7   1.3    rain
2015-12-29            0.0       7.2       0.6   2.6     fog
2015-12-30            0.0       5.6      -1.0   3.4     sun
2015-12-31            0.0       5.6      -2.1   3.5     sun

[1095 rows x 5 columns]

            precipitation  temp_max  temp_min  wind weather
date
2013-01-01            0.0       5.0      -2.8   2.7     sun
2013-01-02            0.0       6.1      -1.1   3.2     sun
2013-01-03            4.1       6.7      -1.7   3.0    rain
2013-01-04            2.5      10.0       2.2   2.8    rain
2013-01-05            3.0       6.7       4.4   3.1    rain
...                   ...       ...       ...   ...     ...
2015-12-27            8.6       4.4       1.7   2.9    rain
2015-12-28            1.5       5.0       1.7   1.3    rain
2015-12-29            0.0       7.2       0.6   2.6     fog
2015-12-30            0.0       5.6      -1.0   3.4     sun
2015-12-31            0.0       5.6      -2.1   3.5     sun

[1095 rows x 5 columns]

In [56]:
# 时间间隔
d1 = pd.Timestamp('2003-04-21')
d2 = pd.Timestamp('2026-04-22')

print(d2-d1)
# <class 'pandas.Timedelta'>    时间间隔类型
print(type(d2-d1))

8402 days 00:00:00
<class 'pandas.Timedelta'>

In [58]:
df = pd.read_csv('data/weather.csv',parse_dates=['date'])

df['delta'] = df['date'] - df['date'][0]
df

           date  precipitation  temp_max  temp_min  wind  weather     delta
0    2012-01-01            0.0      12.8       5.0   4.7  drizzle    0 days
1    2012-01-02           10.9      10.6       2.8   4.5     rain    1 days
2    2012-01-03            0.8      11.7       7.2   2.3     rain    2 days
3    2012-01-04           20.3      12.2       5.6   4.7     rain    3 days
4    2012-01-05            1.3       8.9       2.8   6.1     rain    4 days
...         ...            ...       ...       ...   ...      ...       ...
1456 2015-12-27            8.6       4.4       1.7   2.9     rain 1456 days
1457 2015-12-28            1.5       5.0       1.7   1.3     rain 1457 days
1458 2015-12-29            0.0       7.2       0.6   2.6      fog 1458 days
1459 2015-12-30            0.0       5.6      -1.0   3.4      sun 1459 days
1460 2015-12-31            0.0       5.6      -2.1   3.5      sun 1460 days

[1461 rows x 7 columns]

In [63]:
# 时间序列
days = pd.date_range('2024-03-12',"2026-03-31")
print(days)

# 生成10个时间间隔
days= pd.date_range('2024-03-12',periods=10)
print(days)

DatetimeIndex(['2024-03-12', '2024-03-13', '2024-03-14', '2024-03-15',
               '2024-03-16', '2024-03-17', '2024-03-18', '2024-03-19',
               '2024-03-20', '2024-03-21',
               ...
               '2026-03-22', '2026-03-23', '2026-03-24', '2026-03-25',
               '2026-03-26', '2026-03-27', '2026-03-28', '2026-03-29',
               '2026-03-30', '2026-03-31'],
              dtype='datetime64[us]', length=750, freq='D')
DatetimeIndex(['2024-03-12', '2024-03-13', '2024-03-14', '2024-03-15',
               '2024-03-16', '2024-03-17', '2024-03-18', '2024-03-19',
               '2024-03-20', '2024-03-21'],
              dtype='datetime64[us]', freq='D')

In [67]:
# 重新采样
df = pd.read_csv('data/weather.csv',parse_dates=['date'])
df.set_index('date',inplace=True)

print(df)

df[['temp_max','temp_min']].resample('YE').mean()

            precipitation  temp_max  temp_min  wind  weather
date
2012-01-01            0.0      12.8       5.0   4.7  drizzle
2012-01-02           10.9      10.6       2.8   4.5     rain
2012-01-03            0.8      11.7       7.2   2.3     rain
2012-01-04           20.3      12.2       5.6   4.7     rain
2012-01-05            1.3       8.9       2.8   6.1     rain
...                   ...       ...       ...   ...      ...
2015-12-27            8.6       4.4       1.7   2.9     rain
2015-12-28            1.5       5.0       1.7   1.3     rain
2015-12-29            0.0       7.2       0.6   2.6      fog
2015-12-30            0.0       5.6      -1.0   3.4      sun
2015-12-31            0.0       5.6      -2.1   3.5      sun

[1461 rows x 5 columns]

             temp_max  temp_min
date
2012-12-31  15.276776  7.289617
2013-12-31  16.058904  8.153973
2014-12-31  16.995890  8.662466
2015-12-31  17.427945  8.835616

In [13]:
import pandas as pd

df = pd.read_csv('data/employees.csv')

df
# 分组聚合
df.dropna(subset=['department_id'], inplace=True)

df['department_id'] = df['department_id'].astype('int64')

# 计算不同部门的平均工资

# 查看分组
df.groupby('department_id').groups

df.groupby('department_id').get_group(20)
df2 = df.groupby('department_id')[['salary']].mean()
df2['salary'] = df2['salary'].round(2)

print(df2)

df2 = df2.reset_index()

print(df2)

df2.sort_values('salary', ascending=False)

print(df2)

                 salary
department_id
10              4400.00
20              9500.00
30              4150.00
40              6500.00
50              3475.56
60              5760.00
70             10000.00
80              8955.88
90             19333.33
100             8600.00
110            10150.00
    department_id    salary
0              10   4400.00
1              20   9500.00
2              30   4150.00
3              40   6500.00
4              50   3475.56
5              60   5760.00
6              70  10000.00
7              80   8955.88
8              90  19333.33
9             100   8600.00
10            110  10150.00
    department_id    salary
0              10   4400.00
1              20   9500.00
2              30   4150.00
3              40   6500.00
4              50   3475.56
5              60   5760.00
6              70  10000.00
7              80   8955.88
8              90  19333.33
9             100   8600.00
10            110  10150.00

In [21]:
import pandas as pd

df = pd.read_csv('data/employees.csv')

df
# 分组聚合
df.dropna(subset=['department_id'], inplace=True)

df['department_id'] = df['department_id'].astype('int64')

df2 = df.groupby(['department_id','job_id'])[['salary']].mean()
df2 = df2.reset_index()

df2['salary'] = df2['salary'].round(2)
df2 = df2.sort_values('salary', ascending=False)
print(df2)

    department_id      job_id    salary
13             90     AD_PRES  24000.00
14             90       AD_VP  17000.00
1              20      MK_MAN  13000.00
11             80      SA_MAN  12200.00
16            100      FI_MGR  12000.00
18            110      AC_MGR  12000.00
4              30      PU_MAN  11000.00
10             70      PR_REP  10000.00
12             80      SA_REP   8396.55
17            110  AC_ACCOUNT   8300.00
15            100  FI_ACCOUNT   7920.00
8              50      ST_MAN   7280.00
5              40      HR_REP   6500.00
2              20      MK_REP   6000.00
9              60     IT_PROG   5760.00
0              10     AD_ASST   4400.00
6              50    SH_CLERK   3215.00
7              50    ST_CLERK   2785.00
3              30    PU_CLERK   2780.00